init:
    path:     /init/{re}/{tx_hash}/{from_address}/{to_address}/{sign_link}
    defaults: { _controller: HashReviewsTransactionReviewBundle:Default:init, sign_link: null }
index:
    path:     /
    defaults: { _controller: HashReviewsTransactionReviewBundle:Default:index }
enter_review:
    path:     /review
    defaults: { _controller: HashReviewsTransactionReviewBundle:Default:review }
sign_hash:
    path:     /sign
    defaults: { _controller: HashReviewsTransactionReviewBundle:Default:sign }
success:
    path:     /success
    defaults: { _controller: HashReviewsTransactionReviewBundle:Default:success }
read:
    path:     /{re}/{tx_hash}/{from_address}/{to_address}
    defaults: { _controller: HashReviewsTransactionReviewBundle:Default:read }
reviews:
    path:     /reviews/{search_query}
    defaults: { _controller: HashReviewsTransactionReviewBundle:Default:reviews }
page:
    path:     /page/{slug}
    defaults: { _controller: HashReviewsTransactionReviewBundle:Default:page }