parameters:
#    hash_reviews_transaction_review.example.class: HashReviews\Transaction\ReviewBundle\Example

services:
#    hash_reviews_transaction_review.example:
#        class: %hash_reviews_transaction_review.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
